name: Build dataset

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  build-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build dataset
        run: |
          python src/build_dataset.py \
            -i raw_games_dataset.json \
            -o raw_games_dataset.json \
            -m 200 \
            -d 0 \
            -r 4 \
            -rd 10 \
            --incremental-retry-delay true

      - name: Commit and push dataset
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/raw_games_dataset.csv
          git add data/raw_games_dataset.json
          git add data/ignored_appids.json
          git commit -m "Update raw games dataset"
          git push
