name: Integration Test Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pipeline-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run on test folder
        run: pytest tests/